research_task:
  agent: researcher
  description: |
    Conduct comprehensive, in-depth research on {topic} following this systematic approach:

    1. **Current State Analysis**:
       - What is {topic} and how is it currently defined?
       - What are the core concepts, principles, and technologies involved?
       - What are the current implementations and use cases?
       - What are the major players, companies, and organizations in this space?

    2. **Technical Deep Dive**:
       - What are the underlying technologies and architectures?
       - What are the key algorithms, frameworks, or methodologies?
       - What are the technical challenges and limitations?
       - What are the performance characteristics and benchmarks?

    3. **Market and Industry Analysis**:
       - What is the current market size and growth trajectory?
       - What are the adoption rates and trends?
       - What are the key drivers and barriers to adoption?
       - What are the competitive landscape and positioning?

    4. **Recent Developments and Trends**:
       - What are the latest innovations and breakthroughs (last 12 months)?
       - What are the emerging trends and future directions?
       - What are the upcoming technologies or methodologies?
       - What are the predictions and forecasts from industry experts?

    5. **Real-world Applications**:
       - What are the most successful implementations and case studies?
       - What are the practical applications across different industries?
       - What are the ROI and business impact examples?
       - What are the lessons learned from real-world deployments?

    6. **Challenges and Considerations**:
       - What are the technical challenges and limitations?
       - What are the ethical, legal, or regulatory considerations?
       - What are the security and privacy concerns?
       - What are the scalability and maintenance challenges?

    7. **Future Outlook**:
       - What are the predicted developments in the next 1-3 years?
       - What are the potential disruptive impacts?
       - What are the opportunities and threats?
       - What are the recommendations for organizations and individuals?

    8. **Expert Opinions and Sources**:
       - What do industry experts and thought leaders say about {topic}?
       - What are the most authoritative sources and references?
       - What are the academic research and publications?
       - What are the industry reports and whitepapers?

    **Research Requirements**:
    - Use multiple credible sources (academic papers, industry reports, expert blogs, official documentation)
    - Include specific data points, statistics, and quantitative information
    - Provide direct quotes from experts when relevant
    - Include links to source materials and references
    - Focus on the most recent and relevant information (prioritize last 6 months)
    - Ensure accuracy and verify information from multiple sources
    - Be comprehensive but also highlight the most important and impactful findings

  expected_output: |
    A comprehensive research report on {topic} structured as follows:

    ## Executive Summary
    Brief overview of key findings and insights (2-3 paragraphs)

    ## Current State and Definition
    - Clear definition and scope of {topic}
    - Core concepts and principles
    - Current implementations and use cases
    - Key players and organizations

    ## Technical Analysis
    - Underlying technologies and architectures
    - Key algorithms, frameworks, or methodologies
    - Technical specifications and requirements
    - Performance characteristics and benchmarks

    ## Market and Industry Landscape
    - Market size, growth, and adoption trends
    - Industry drivers and barriers
    - Competitive landscape analysis
    - Regional and sector-specific insights

    ## Recent Developments and Innovations
    - Latest breakthroughs and innovations (last 12 months)
    - Emerging trends and technologies
    - Notable announcements and releases
    - Expert predictions and forecasts

    ## Real-world Applications and Case Studies
    - Successful implementation examples
    - Industry-specific applications
    - ROI and business impact data
    - Lessons learned and best practices

    ## Challenges and Considerations
    - Technical challenges and limitations
    - Ethical, legal, and regulatory issues
    - Security and privacy concerns
    - Scalability and maintenance considerations

    ## Future Outlook and Predictions
    - Short-term developments (1-2 years)
    - Long-term trends and predictions
    - Potential disruptive impacts
    - Strategic recommendations

    ## Expert Insights and Sources
    - Key expert opinions and quotes
    - Authoritative sources and references
    - Academic research highlights
    - Industry report summaries

    **Format Requirements**:
    - Use proper markdown formatting with headers, lists, and emphasis
    - Include specific data points and statistics
    - Provide source links and references
    - Ensure comprehensive coverage of all research areas
    - Target length: 2000-4000 words of detailed, well-structured content
    - Focus on actionable insights and practical information

  metadata:
    type: research
    format: markdown
    min_length: 2000
    max_length: 4000
    research_depth: comprehensive
    source_requirements: multiple_credible_sources

technical_writer_task:
  agent: technical_writer
  description: |
    Using the comprehensive research provided, create a detailed, engaging technical blog post about {topic} that follows these guidelines:

    1. **Content Structure and Flow**:
       - Start with a compelling introduction that hooks the reader
       - Use the research data to create a logical, well-structured narrative
       - Include clear section headers and subheaders for easy navigation
       - End with a strong conclusion that summarizes key takeaways

    2. **Technical Depth and Clarity**:
       - Explain complex concepts in simple, accessible language
       - Use analogies and real-world examples to illustrate technical points
       - Include relevant code snippets, diagrams, or technical specifications
       - Break down complex processes into step-by-step explanations

    3. **Data-Driven Content**:
       - Incorporate specific statistics, metrics, and data points from the research
       - Use charts, graphs, or visual representations where appropriate
       - Include case studies and real-world examples
       - Provide concrete evidence to support claims and recommendations

    4. **SEO and Readability Optimization**:
       - Use relevant keywords naturally throughout the content
       - Include meta descriptions and proper heading hierarchy
       - Optimize for featured snippets and search visibility
       - Ensure content is scannable with bullet points and numbered lists

    5. **Engagement and Value**:
       - Address common questions and pain points related to {topic}
       - Provide actionable insights and practical recommendations
       - Include expert quotes and industry insights
       - Add internal and external links for further reading

    6. **Technical Accuracy**:
       - Ensure all technical information is accurate and up-to-date
       - Verify code snippets and technical specifications
       - Cross-reference information with authoritative sources
       - Include disclaimers where appropriate

    7. **Visual and Interactive Elements**:
       - Suggest relevant images, diagrams, or infographics
       - Include code examples with proper syntax highlighting
       - Add callout boxes for important tips or warnings
       - Use tables to organize complex information

    8. **Audience Consideration**:
       - Write for both technical and non-technical audiences
       - Provide context and background information where needed
       - Use progressive disclosure for complex topics
       - Include a glossary of technical terms if necessary

  expected_output: |
    A comprehensive, well-structured technical blog post about {topic} that includes:

    ## Introduction
    - Engaging hook and problem statement
    - Brief overview of what the article will cover
    - Target audience and value proposition

    ## Main Content Sections
    - Detailed explanations of key concepts
    - Technical specifications and implementations
    - Real-world examples and case studies
    - Data-driven insights and statistics
    - Expert opinions and industry trends

    ## Technical Implementation
    - Code examples and snippets
    - Step-by-step guides or tutorials
    - Best practices and recommendations
    - Common pitfalls and solutions

    ## Analysis and Insights
    - Market analysis and trends
    - Performance comparisons and benchmarks
    - ROI and business impact analysis
    - Future predictions and recommendations

    ## Conclusion
    - Summary of key takeaways
    - Actionable next steps
    - Call-to-action for readers

    **Content Requirements**:
    - Minimum 2500 words of high-quality, detailed content
    - Proper markdown formatting with headers, lists, and emphasis
    - Include relevant links and references
    - Use data and statistics from the research
    - Ensure technical accuracy and clarity
    - Optimize for both human readers and search engines

  metadata:
    type: content
    format: markdown
    min_length: 2500
    max_length: 5000
    seo_optimized: true
    technical_depth: comprehensive
    audience: mixed_technical

technical_reviewer_task:
  agent: technical_reviewer
  description: |
    Conduct a comprehensive review of the technical blog post about {topic} following these evaluation criteria:

    1. **Content Quality and Depth**:
       - Is the content comprehensive and detailed enough?
       - Does it cover all important aspects of {topic}?
       - Is the technical information accurate and up-to-date?
       - Are there any gaps in the content that need to be addressed?

    2. **Technical Accuracy and Completeness**:
       - Verify all technical claims, specifications, and data points
       - Check for any inaccuracies or outdated information
       - Ensure code examples are correct and functional
       - Validate all links, references, and sources

    3. **Readability and Clarity**:
       - Is the content accessible to the target audience?
       - Are complex concepts explained clearly?
       - Is the language appropriate for both technical and non-technical readers?
       - Are there any confusing or ambiguous sections?

    4. **Structure and Organization**:
       - Is the content well-organized with logical flow?
       - Are headings and subheadings used effectively?
       - Is the information presented in a logical sequence?
       - Are there clear transitions between sections?

    5. **SEO and Technical Optimization**:
       - Are relevant keywords used naturally throughout the content?
       - Is the heading hierarchy optimized for search engines?
       - Are meta descriptions and titles appropriate?
       - Is the content optimized for featured snippets?

    6. **Engagement and Value**:
       - Does the content provide real value to readers?
       - Are there actionable insights and recommendations?
       - Is the content engaging and interesting to read?
       - Are there appropriate calls-to-action?

    7. **Data and Evidence**:
       - Are claims supported by credible sources and data?
       - Are statistics and metrics properly cited?
       - Are expert quotes and insights relevant and accurate?
       - Is there sufficient evidence to support recommendations?

    8. **Visual and Interactive Elements**:
       - Are code examples properly formatted and highlighted?
       - Are tables and lists used effectively?
       - Are there suggestions for relevant images or diagrams?
       - Is the content visually appealing and scannable?

  expected_output: |
    A comprehensive review report with the following sections:

    ## Executive Summary
    Overall assessment of the blog post quality and readiness for publication

    ## Content Quality Assessment
    - **Strengths**: What aspects of the content are particularly strong
    - **Areas for Improvement**: Specific suggestions for enhancing the content
    - **Missing Elements**: Any important topics or information that should be added
    - **Technical Accuracy**: Verification of all technical claims and data

    ## Readability and Structure Analysis
    - **Clarity**: Assessment of how well complex concepts are explained
    - **Organization**: Evaluation of content structure and flow
    - **Audience Appropriateness**: How well the content serves the target audience
    - **Navigation**: Effectiveness of headings and content organization

    ## SEO and Technical Optimization Review
    - **Keyword Usage**: Assessment of keyword integration and optimization
    - **Technical SEO**: Evaluation of heading hierarchy, meta information, etc.
    - **Content Optimization**: Suggestions for improving search visibility
    - **Link Strategy**: Review of internal and external links

    ## Specific Recommendations
    - **Content Additions**: Specific content that should be added or expanded
    - **Content Revisions**: Specific sections that need rewriting or clarification
    - **Technical Improvements**: Code examples, diagrams, or technical details to add
    - **Formatting Suggestions**: Improvements to structure, formatting, or presentation

    ## Quality Score and Readiness Assessment
    - **Overall Quality Score**: 1-10 rating with justification
    - **Publication Readiness**: Whether the content is ready for publication
    - **Priority Fixes**: Critical issues that must be addressed before publication
    - **Optional Enhancements**: Improvements that could be made for better quality

    **Review Requirements**:
    - Be thorough and constructive in feedback
    - Provide specific, actionable recommendations
    - Focus on both technical accuracy and user experience
    - Consider SEO and content marketing best practices
    - Ensure feedback is clear and implementable

  metadata:
    type: review
    format: markdown
    review_depth: comprehensive
    focus_areas:
      [content_quality, technical_accuracy, readability, seo, engagement]

technical_publisher_task:
  agent: technical_publisher
  description: |
    1. After getting feedback from the technical reviewer, update the technical blog post and make it more popular based on the feedback
    2. Add metadata for blog scheduling:
       - Title
       - Author
       - Publication date
       - Tags
       - Categories
       - Reading time estimate
    3. Format the content for blog platform compatibility
    4. Save content as a markdown file with proper format using the save_blog_post function
    5. Ensure the output directory exists and is accessible
  expected_output: >
    A technical blog post about {topic} in more detail and easy to understand
    Formatted as markdown without '```'
  metadata:
    type: publish
    format: markdown
    markdown: true
    output_file: '{timestamp}_{topic}_blog_post.md'
    output_dir: './output'
    frontmatter:
      title: '{topic} - Technical Deep Dive'
      author: 'AI Blog Writer'
      date: '{current_date}'
      timestamp: '{timestamp}'
      slug: '{topic}-technical-deep-dive'
      tags: ['{topic}', 'technology', 'tutorial']
      categories: ['Technical']
      reading_time: '{estimated_time}'
      status: 'published'
      featured: false
